name = "rubiks-snake"
version = "0.1.0"
defaultTargets = ["RubiksSnake"]

[[lean_lib]]
name = "RubiksSnake"
roots = ["RubiksSnake"]

[[lean_lib]]
name = "RubiksSnakeComputation"
roots = ["RubiksSnake.SnAsymptotic.Computation"]
precompileModules = true

[[lean_lib]]
name = "RubiksSnakePrunedComputation"
roots = ["RubiksSnake.SnAsymptotic.PrunedComputation"]
precompileModules = true

[[lean_lib]]
name = "RubiksSnakeCapComputation"
roots = ["RubiksSnake.SnAsymptotic.CapComputation"]
precompileModules = true

[[lean_lib]]
name = "RubiksSnakePrefixComputation"
roots = ["RubiksSnake.SnAsymptotic.PrefixComputation"]
precompileModules = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.33.1"
