name = "rubiks-snake"
version = "0.1.0"
defaultTargets = ["RubiksSnake"]

[[lean_lib]]
name = "RubiksSnake"
roots = ["RubiksSnake"]

[[lean_lib]]
name = "RubiksSnakeComputation"
precompileModules = true

[[lean_lib]]
name = "RubiksSnakePrunedComputation"
precompileModules = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.33.1"
